# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b10cbffde5783b888bf57e25ec775eb3e718961bec2d2fad434174263311b44d5ea08beeaa2e00729f1908265c9456678dce3df156764443aaee09ec9d3385fd

test:
  secret_key_base: 4bdc45019e3cefb2a7c6efbe694de01e27fbf5800803bebff03d0400ae72ba3f79f41ad4b2e0ad3033f3f81fbe893d2114ba41e1aa3da7934e141915a3571e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
